# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2025 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# HAL Feature Profile for Motion Sensor
#
# This file defines the platform-specific capabilities for motion sensors.
# One entry per physical/logical sensor on the platform.
#
# Capabilities Mapping:
#   Fields marked with "Capabilities.*" correspond to immutable values returned
#   by IMotionSensor.getCapabilities() and must match at runtime.
#
# Configuration Fields:
#   Other fields define operational defaults, supported modes, and platform-specific
#   requirements for validation and testing.

sensor:
  motion:
    # ========================================================================
    # CAPABILITIES (Immutable - returned by getCapabilities())
    # ========================================================================
    - id: 0                                   # IMotionSensor.Id.value
      sensorName: "PIR-Front-1"               # Capabilities.sensorName
      sensitivity_range:
        minSensitivity: 1                     # Capabilities.minSensitivity
        maxSensitivity: 10                    # Capabilities.maxSensitivity
      supportsDeepSleepAutonomy: true         # Capabilities.supportsDeepSleepAutonomy
      
      # ========================================================================
      # OPERATIONAL CONFIGURATION (Platform-specific defaults and constraints)
      # ========================================================================
      operational_modes:
        - MOTION
        - NO_MOTION
      default_mode: MOTION
      timing:
        no_motion_seconds: 5     # Default inactivity window before NO_MOTION event
        active_start_seconds: 0  # Activation delay after start()
        active_stop_seconds: 0   # Continuous monitoring until stop()
      active_windows:
        # Example: Monitor during business hours (9am-5pm) and evening (8pm-10pm)
        - startTimeOfDaySeconds: 32400  # 09:00:00 (9 * 3600)
          endTimeOfDaySeconds: 61200    # 17:00:00 (17 * 3600)
        - startTimeOfDaySeconds: 72000  # 20:00:00 (20 * 3600)
          endTimeOfDaySeconds: 79200    # 22:00:00 (22 * 3600)
        # Leave empty or set both values to 0 for 24-hour monitoring
      requirements:
        min_reaction_time_ms: 500  # Minimum reaction time to motion events
      notes:
        - "Front-facing PIR motion detector."
        - "Supports autonomous operation during deep sleep."
        - "Active windows can be configured via setActiveWindows()."
