/*
 * If not stated otherwise in this file or this component's LICENSE file the
 * following copyright and licenses apply:
 *
 * Copyright 2026 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.rdk.hal.audiodecoder;

/**
 * @brief     The figures audiodecoder measures.
 * @author    Gerald Weatherup
 *
 * THIS FILE IS GENERATED by scripts/kvcc.py from
 * audiodecoder/kvc/current/audiodecoder.kvc (vocabulary 1.0,
 * schema 1). Do not edit: declare the key there and
 * regenerate, so an identifier is derived rather than typed.
 */

/**
 * @brief The figures audiodecoder measures.
 *
 * A value carries aggregation semantics, so its identifier composes with its
 * kind as well as its unit. Serving one in the wrong unit, or reading it on
 * the wrong cadence for its kind, is then a mismatch a consumer can detect
 * rather than a plausible wrong number.
 */

@VintfStability
@Backing(type="long")
enum Metric
{

    /**
     * `av.audio_decoder.frames_decoded` — frames, counter. Audio access units
     * decoded and emitted at the decoder output, one per emitted access unit.
     * Counted from instance creation and never reset on flush or seek.
     */
    FRAMES_DECODED = 0x23c94a86f7865005,

    /**
     * `av.audio_decoder.frames_dropped` — frames, counter. Audio frames
     * discarded before output, whether through an xrun or because they were
     * undecodable. Decoder-internal, and excluded from frames_decoded.
     */
    FRAMES_DROPPED = 0x748c7fd20b15139d,

    /**
     * `av.audio_decoder.decode_errors` — events, counter. Audio decode-error
     * occurrences. A distinct axis from frames_dropped, exactly as on
     * av.video_decoder: an error need not drop a frame, and a drop need not
     * be an error.
     */
    DECODE_ERRORS = 0x577de621243f5a94,

    /**
     * `av.audio_decoder.decode_latency_sum_us` — us, counter. Running sum of
     * per-frame audio decode latency, from the access unit being queued at
     * the input to the frame being emitted at the output. Paired with
     * frames_decoded.
     */
    DECODE_LATENCY_SUM_US = 0x1b3e9a9b42d47872,

    /**
     * `av.audio_decoder.last_decode_error_pts_ms` — ms, current. Stream PTS
     * at detection of the most recent audio decode error, within one frame
     * interval. Read with decode_errors. Left undeclared where no PTS is
     * derivable, and never served as -1.
     */
    LAST_DECODE_ERROR_PTS_MS = 0x5d4a1b8bfa10cbbe,

    /**
     * `av.audio_decoder.last_decode_error_reason` — none, current.
     * Classification of the most recent audio decode error. This is the value
     * a consumer branches on, and what makes the fault comparable across
     * SoCs.
     */
    LAST_DECODE_ERROR_REASON = 0x10596fb80be50427,

    /**
     * `av.audio_decoder.last_decode_error_vendor_code` — none, current. The
     * SoC's own code for the same fault, carried through uninterpreted. For
     * vendor diagnosis, and never branched on.
     */
    LAST_DECODE_ERROR_VENDOR_CODE = 0x7129e447242c26d5,
}
