# Auto-generated by scripts/gen_recipes.py from audiomixer/0.3.0.0/interface.yaml.
# Do not hand-edit - regenerate with: ./scripts/gen_recipes.py
SUMMARY = "RDK HAL AIDL interface library: audiomixer (v0.3.0.0)"

HALIF_MODULE = "audiomixer"
HALIF_VERSION = "0.3.0.0"
PV = "0.3.0.0"

# From audiomixer/0.3.0.0/interface.yaml imports: audiodecoder@0.2.0.0, audiosink@0.2.0.0, common@0.2.0.0
DEPENDS += "rdk-halif-audiodecoder rdk-halif-audiosink rdk-halif-common"

inherit rdk-halif-module
