# Auto-generated by scripts/gen_recipes.py for audiosink/0.1.0.0.
# Do not hand-edit - regenerate with: ./scripts/gen_recipes.py
SUMMARY = "RDK HAL AIDL interface library: audiosink (v0.1.0.0)"

HALIF_MODULE = "audiosink"
HALIF_VERSION = "0.1.0.0"
PV = "0.1.0.0"

# Links: audiodecoder@0.1.0.0, avclock@0.1.0.0, common@0.1.0.0
DEPENDS += "rdk-halif-audiodecoder rdk-halif-avclock rdk-halif-common"

inherit rdk-halif-module
