# Auto-generated by scripts/gen_recipes.py from indicator/0.1.0.0/interface.yaml.
# Do not hand-edit - regenerate with: ./scripts/gen_recipes.py
SUMMARY = "RDK HAL AIDL interface library: indicator (v0.1.0.0)"

HALIF_MODULE = "indicator"
HALIF_VERSION = "0.1.0.0"
PV = "0.1.0.0"

# No interface.yaml imports - depends only on the Binder SDK.

inherit rdk-halif-module
