# Auto-generated by scripts/gen_recipes.py for audiomixer/0.2.0.0.
# Do not hand-edit - regenerate with: ./scripts/gen_recipes.py
SUMMARY = "RDK HAL AIDL interface library: audiomixer (v0.2.0.0)"

HALIF_MODULE = "audiomixer"
HALIF_VERSION = "0.2.0.0"
PV = "0.2.0.0"

# Links: audiodecoder@0.2.0.0, audiosink@0.2.0.0, common@0.2.0.0
DEPENDS += "rdk-halif-audiodecoder rdk-halif-audiosink rdk-halif-common"

inherit rdk-halif-module
