# Auto-generated by scripts/gen_recipes.py for audiomixer/0.1.0.1.
# Do not hand-edit - regenerate with: ./scripts/gen_recipes.py
SUMMARY = "RDK HAL AIDL interface library: audiomixer (v0.1.0.1)"

HALIF_MODULE = "audiomixer"
HALIF_VERSION = "0.1.0.1"
PV = "0.1.0.1"

# Links: audiodecoder@0.1.0.0, common@0.1.0.0
DEPENDS += "rdk-halif-audiodecoder rdk-halif-common"

inherit rdk-halif-module
