# Auto-generated by scripts/gen_recipes.py - do not hand-edit.
# One recipe per component; a build configuration selects the version per
# component with HALIF_VERSION:pn-rdk-halif-hdmioutput (see scripts/gen_team_conf.py).

SUMMARY = "RDK HAL AIDL interface library: hdmioutput"

HALIF_MODULE = "hdmioutput"
# Released versions: 0.1.0.0. Default is the latest.
HALIF_VERSION ??= "0.1.0.0"
# Sibling deps by version (resolved from each snapshot).
HALIF_SIBLINGS = "${@ {'0.1.0.0': 'rdk-halif-common'}.get(d.getVar('HALIF_VERSION'), '') }"

inherit rdk-halif-module
