# Auto-generated by scripts/gen_recipes.py for planecontrol/0.1.0.0.
# Do not hand-edit - regenerate with: ./scripts/gen_recipes.py
SUMMARY = "RDK HAL AIDL interface library: planecontrol (v0.1.0.0)"

HALIF_MODULE = "planecontrol"
HALIF_VERSION = "0.1.0.0"
PV = "0.1.0.0"

# Links: common@0.2.0.0, videodecoder@0.2.0.0
DEPENDS += "rdk-halif-common rdk-halif-videodecoder"

inherit rdk-halif-module
