# Auto-generated by scripts/gen_recipes.py - do not hand-edit.
# One recipe per component; a build configuration selects the version per
# component with HALIF_VERSION:pn-rdk-halif-indicator (see scripts/gen_team_conf.py).

SUMMARY = "RDK HAL AIDL interface library: indicator"

HALIF_MODULE = "indicator"
# Released versions: 0.1.0.0. Default is the latest.
HALIF_VERSION ??= "0.1.0.0"

inherit rdk-halif-module
