# Auto-generated by scripts/gen_recipes.py from audiosink/0.2.0.0/interface.yaml.
# Do not hand-edit - regenerate with: ./scripts/gen_recipes.py
SUMMARY = "RDK HAL AIDL interface library: audiosink (v0.2.0.0)"

HALIF_MODULE = "audiosink"
HALIF_VERSION = "0.2.0.0"
PV = "0.2.0.0"

# From audiosink/0.2.0.0/interface.yaml imports: audiodecoder@0.2.0.0, avclock@0.2.0.0, common@0.2.0.0
DEPENDS += "rdk-halif-audiodecoder rdk-halif-avclock rdk-halif-common"

inherit rdk-halif-module
