/*
 * If not stated otherwise in this file or this component's LICENSE file the
 * following copyright and licenses apply:
 *
 * Copyright 2026 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.rdk.hal.videodecoder;

/**
 * @brief     What describes an occurrence videodecoder raised.
 * @author    Gerald Weatherup
 *
 * THIS FILE IS GENERATED by scripts/kvcc.py from
 * videodecoder/kvc/current/videodecoder.kvc (vocabulary 1.0,
 * schema 1). Do not edit: declare the key there and
 * regenerate, so an identifier is derived rather than typed.
 */

/**
 * @brief What describes an occurrence videodecoder raised.
 *
 * An attribute locates and classifies an occurrence rather than measuring
 * it, so its identifier composes without a kind term. A value an occurrence
 * measured does carry a kind. Both appear in MetricEvent, in the array that
 * says which it is.
 */

@VintfStability
@Backing(type="long")
enum MetricEventAttribute
{

    /**
     * `av.video_decoder.decode_error.reason` — none. Classification of this
     * fault, from the same closed vocabulary as last_decode_error_reason. The
     * value a consumer branches on.
     */
    DECODE_ERROR_REASON = 0x1eb66b82bd8ad2f9,

    /**
     * `av.video_decoder.decode_error.vendor_code` — none. The SoC's own error
     * code for this fault, carried through uninterpreted. For vendor
     * diagnosis, and never branched on.
     */
    DECODE_ERROR_VENDOR_CODE = 0x44486ad4e1aa81ab,

    /**
     * `av.video_decoder.decode_error.pts_ms` — ms. Stream PTS at detection,
     * within one frame interval. Absent where the SoC cannot derive a PTS at
     * all, and NOT_AVAILABLE where it can but could not at this instant.
     * Never sent as -1.
     */
    DECODE_ERROR_PTS_MS = 0x6f31b4b8fbc5b36b,
}
