/*
 * If not stated otherwise in this file or this component's LICENSE file the
 * following copyright and licenses apply:
 *
 * Copyright 2026 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.rdk.hal.videodecoder;

/**
 * @brief     The figures videodecoder measures.
 * @author    Gerald Weatherup
 *
 * THIS FILE IS GENERATED by scripts/kvcc.py from
 * videodecoder/kvc/current/videodecoder.kvc (vocabulary 1.0,
 * schema 1). Do not edit: declare the key there and
 * regenerate, so an identifier is derived rather than typed.
 */

/**
 * @brief The figures videodecoder measures.
 *
 * A value carries aggregation semantics, so its identifier composes with its
 * kind as well as its unit. Serving one in the wrong unit, or reading it on
 * the wrong cadence for its kind, is then a mismatch a consumer can detect
 * rather than a plausible wrong number.
 */

@VintfStability
@Backing(type="long")
enum Metric
{

    /**
     * `av.video_decoder.frames_decoded` — frames, counter. Compressed frames
     * the decoder has decoded and emitted at its output, post-decode and pre-
     * sink. One per emitted frame, counted from instance creation and never
     * reset on flush or seek.
     */
    FRAMES_DECODED = 0x63c81c7efbe7e743,

    /**
     * `av.video_decoder.frames_dropped` — frames, counter. Frames the decoder
     * discarded before output — undecodable through corruption or unsupported
     * format, or shed under decode overload. Excludes presentation-side
     * drops, which belong to the video sink. A frame counted here is not also
     * in frames_decoded.
     */
    FRAMES_DROPPED = 0x2c67d98cc76e6fb7,

    /**
     * `av.video_decoder.decode_errors` — events, counter. Decode-error
     * occurrences such as a bitstream or NAL parse failure or a codec fault.
     * Decoder-internal, and a distinct axis from frames_dropped: an error
     * need not drop a frame, and a drop need not be an error.
     */
    DECODE_ERRORS = 0x070bb5fa11ef497b,

    /**
     * `av.video_decoder.decode_latency_sum_us` — us, counter. Running sum of
     * per-frame decode latency, measured from the compressed access unit
     * being queued to the decoder input until the frame is emitted at its
     * output. Mean latency is this divided by frames_decoded.
     */
    DECODE_LATENCY_SUM_US = 0x4e69bac967d540b7,

    /**
     * `av.video_decoder.last_decode_error_pts_ms` — ms, current. Stream PTS
     * at detection of the most recent decode error, within one frame
     * interval. Read with decode_errors, which says how many there were while
     * this says where the newest one was. Left undeclared where the SoC
     * cannot derive a PTS, and never served as -1.
     */
    LAST_DECODE_ERROR_PTS_MS = 0x14debdd0bbd63a14,

    /**
     * `av.video_decoder.last_decode_error_reason` — none, current.
     * Classification of the most recent decode error. This is the value a
     * consumer branches on, and what makes the fault comparable across SoCs.
     */
    LAST_DECODE_ERROR_REASON = 0x4fda2a3cf3d7dc09,

    /**
     * `av.video_decoder.last_decode_error_vendor_code` — none, current. The
     * SoC's own error code for the same fault, carried through uninterpreted.
     * For vendor diagnosis, and never branched on.
     */
    LAST_DECODE_ERROR_VENDOR_CODE = 0x26d18e085c02dfd4,
}
