# Auto-generated by scripts/gen_recipes.py from hdmiinput/0.1.0.0/interface.yaml.
# Do not hand-edit - regenerate with: ./scripts/gen_recipes.py
SUMMARY = "RDK HAL AIDL interface library: hdmiinput (v0.1.0.0)"

HALIF_MODULE = "hdmiinput"
HALIF_VERSION = "0.1.0.0"
PV = "0.1.0.0"

# From hdmiinput/0.1.0.0/interface.yaml imports: common@0.2.0.0
DEPENDS += "rdk-halif-common"

inherit rdk-halif-module
