# Auto-generated by scripts/gen_recipes.py for deepsleep/0.1.0.0.
# Do not hand-edit - regenerate with: ./scripts/gen_recipes.py
SUMMARY = "RDK HAL AIDL interface library: deepsleep (v0.1.0.0)"

HALIF_MODULE = "deepsleep"
HALIF_VERSION = "0.1.0.0"
PV = "0.1.0.0"

# No sibling dependencies - links only the Binder SDK.

inherit rdk-halif-module
