/*
 * If not stated otherwise in this file or this component's LICENSE file the
 * following copyright and licenses apply:
 *
 * Copyright 2026 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.rdk.hal.drm;

/**
 * @brief     Identifier of the element drm reports.
 * @author    Gerald Weatherup
 *
 * THIS FILE IS GENERATED by scripts/kvcc.py from
 * drm/kvc/current/drm.kvc (vocabulary 1.0,
 * schema 1). Do not edit: declare the key there and
 * regenerate, so an identifier is derived rather than typed.
 */

/**
 * @brief Identifier of the element drm reports.
 *
 * MetricGroup.id carries this. The instance is not part of it, because how
 * many are live is a property of the moment rather than of the contract; it
 * is carried as an attribute instead.
 */

@VintfStability
@Backing(type="long")
enum MetricElement
{

    /**
     * `av.drm` — 2 instance(s), captured no slower than every 50 ms.
     */
    DRM = 0x3be5340700505073,
}
