/*
 * If not stated otherwise in this file or this component's LICENSE file the
 * following copyright and licenses apply:
 *
 * Copyright 2026 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.rdk.hal.drm;

/**
 * @brief     The figures drm measures.
 * @author    Gerald Weatherup
 *
 * THIS FILE IS GENERATED by scripts/kvcc.py from
 * drm/kvc/current/drm.kvc (vocabulary 1.0,
 * schema 1). Do not edit: declare the key there and
 * regenerate, so an identifier is derived rather than typed.
 */

/**
 * @brief The figures drm measures.
 *
 * A value carries aggregation semantics, so its identifier composes with its
 * kind as well as its unit. Serving one in the wrong unit, or reading it on
 * the wrong cadence for its kind, is then a mismatch a consumer can detect
 * rather than a plausible wrong number.
 */

@VintfStability
@Backing(type="long")
enum Metric
{

    /**
     * `av.drm.decrypt_count` — operations, counter. Decrypt operations
     * completed, summed across the key sessions this media session holds. The
     * denominator for mean decrypt latency.
     */
    DECRYPT_COUNT = 0x01c6bee68b39b413,

    /**
     * `av.drm.decrypt_errors` — events, counter. Decrypt operations that
     * failed on a key already held. Distinct from a licence that was never
     * obtained, which is not vendor-observable and is not counted here.
     */
    DECRYPT_ERRORS = 0x5db0ea33fec21035,

    /**
     * `av.drm.decrypt_latency_sum_us` — us, counter. Sum of decrypt operation
     * latency. Paired with decrypt_count, so the mean decrypt latency is this
     * divided by that.
     */
    DECRYPT_LATENCY_SUM_US = 0x6663f481e5048044,
}
