# Auto-generated by scripts/gen_recipes.py for firmwareupdate/0.2.0.0.
# Do not hand-edit - regenerate with: ./scripts/gen_recipes.py
SUMMARY = "RDK HAL AIDL interface library: firmwareupdate (v0.2.0.0)"

HALIF_MODULE = "firmwareupdate"
HALIF_VERSION = "0.2.0.0"
PV = "0.2.0.0"

# No sibling dependencies - links only the Binder SDK.

inherit rdk-halif-module
