# Auto-generated by scripts/gen_recipes.py from avclock/0.2.0.0/interface.yaml.
# Do not hand-edit - regenerate with: ./scripts/gen_recipes.py
SUMMARY = "RDK HAL AIDL interface library: avclock (v0.2.0.0)"

HALIF_MODULE = "avclock"
HALIF_VERSION = "0.2.0.0"
PV = "0.2.0.0"

# From avclock/0.2.0.0/interface.yaml imports: common@0.2.0.0
DEPENDS += "rdk-halif-common"

inherit rdk-halif-module
