#!/usr/bin/env python3
#/**
# * Copyright 2026 RDK Management
# *
# * Licensed under the Apache License, Version 2.0 (the "License");
# * you may not use this file except in compliance with the License.
# * You may obtain a copy of the License at
# *
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *
# * SPDX-License-Identifier: Apache-2.0
# */
"""Generate the meta-rdk-halif BitBake recipes from each snapshot's interface.yaml.

For every component, the latest released snapshot (highest X.Y.Z.W) is emitted as
  meta-rdk-halif/recipes-halif/rdk-halif-<comp>/rdk-halif-<comp>_<ver>.bb
with DEPENDS derived from that snapshot's interface.yaml `imports:`. The recipe
carries no dependency list of its own beyond what interface.yaml declares - the
imports are the single source of truth.

The latest-per-component cohort is internally consistent: every import references
the latest version of the imported component, so DEPENDS maps by component name
(rdk-halif-<dep>). The generator asserts this and fails loudly if an import ever
references a non-latest dependency, so cohort drift cannot ship silently.

Usage:
  scripts/gen_recipes.py            # regenerate recipes under meta-rdk-halif/
  scripts/gen_recipes.py --check    # verify recipes are up to date (no writes)
"""
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LAYER = os.path.join(REPO_ROOT, "tests", "fake-yocto", "meta-rdk-halif")
RECIPES_DIR = os.path.join(LAYER, "recipes-halif")

VER_RE = re.compile(r"^\d+\.\d+\.\d+\.\d+$")


def version_tuple(ver):
    return tuple(int(p) for p in ver.split("."))


def parse_interface_yaml(path):
    """Return (name, imports) where imports is [(dep_comp, dep_ver), ...].

    Hand-parsed to avoid a PyYAML dependency (release tooling must run without
    extra packages). The schema is fixed and simple:
        aidl_interface:
          name: <comp>
          imports:
            - <dep>@<X.Y.Z.W>
            - ...
          imports: []          # (leaf component)
    """
    name = None
    imports = []
    in_imports = False
    with open(path) as fh:
        for line in fh:
            stripped = line.rstrip("\n")
            m = re.match(r"^\s+name:\s*(\S+)\s*$", stripped)
            if m:
                name = m.group(1)
                continue
            m = re.match(r"^\s+imports:\s*(\[\s*\])?\s*$", stripped)
            if m:
                in_imports = True
                continue
            if in_imports:
                m = re.match(r"^\s+-\s*(\S+)@(\S+)\s*$", stripped)
                if m:
                    imports.append((m.group(1), m.group(2)))
                    continue
                # A non-list, less-indented line ends the imports block.
                if stripped and not stripped[0].isspace():
                    in_imports = False
                elif re.match(r"^\s+\S+:", stripped):
                    in_imports = False
    return name, imports


def discover_latest():
    """Map component -> (latest_version, interface_yaml_path)."""
    latest = {}
    for comp in sorted(os.listdir(REPO_ROOT)):
        comp_dir = os.path.join(REPO_ROOT, comp)
        if not os.path.isdir(comp_dir) or comp.startswith("."):
            continue
        versions = []
        for ver in os.listdir(comp_dir):
            if VER_RE.match(ver) and os.path.isfile(
                os.path.join(comp_dir, ver, "interface.yaml")
            ):
                versions.append(ver)
        if not versions:
            continue
        top = max(versions, key=version_tuple)
        latest[comp] = (top, os.path.join(comp_dir, top, "interface.yaml"))
    return latest


HEADER = """# Auto-generated by scripts/gen_recipes.py from {rel}.
# Do not hand-edit - regenerate with: ./scripts/gen_recipes.py
"""

BODY = """\
SUMMARY = "RDK HAL AIDL interface library: {comp} (v{ver})"

HALIF_MODULE = "{comp}"
HALIF_VERSION = "{ver}"
PV = "{ver}"
{depends}
inherit rdk-halif-module
"""


def recipe_text(comp, ver, rel, imports):
    if imports:
        dep_line = (
            "\n# From {rel} imports: {raw}\nDEPENDS += \"{deps}\"\n".format(
                rel=rel,
                raw=", ".join("%s@%s" % (d, v) for d, v in imports),
                deps=" ".join("rdk-halif-%s" % d for d, _ in imports),
            )
        )
    else:
        dep_line = "\n# No interface.yaml imports - depends only on the Binder SDK.\n"
    return HEADER.format(rel=rel) + BODY.format(
        comp=comp, ver=ver, depends=dep_line
    )


def main():
    check = "--check" in sys.argv[1:]
    latest = discover_latest()

    # Consistency: every import must reference the latest version of its dep.
    errors = []
    for comp, (ver, iface) in latest.items():
        _, imports = parse_interface_yaml(iface)
        for dep, dver in imports:
            if dep not in latest:
                errors.append(
                    "%s@%s imports unknown component %s@%s" % (comp, ver, dep, dver)
                )
            elif latest[dep][0] != dver:
                errors.append(
                    "%s@%s imports %s@%s but latest %s is %s (cohort drift)"
                    % (comp, ver, dep, dver, dep, latest[dep][0])
                )
    if errors:
        sys.stderr.write("gen_recipes: cohort inconsistency:\n")
        for e in errors:
            sys.stderr.write("  - %s\n" % e)
        return 2

    stale = []
    written = 0
    for comp, (ver, iface) in sorted(latest.items()):
        name, imports = parse_interface_yaml(iface)
        rel = os.path.relpath(iface, REPO_ROOT)
        text = recipe_text(comp, ver, rel, imports)
        out_dir = os.path.join(RECIPES_DIR, "rdk-halif-%s" % comp)
        out = os.path.join(out_dir, "rdk-halif-%s_%s.bb" % (comp, ver))
        existing = open(out).read() if os.path.isfile(out) else None
        if existing == text:
            continue
        if check:
            stale.append(os.path.relpath(out, REPO_ROOT))
            continue
        os.makedirs(out_dir, exist_ok=True)
        with open(out, "w") as fh:
            fh.write(text)
        written += 1
        print("  wrote %s" % os.path.relpath(out, REPO_ROOT))

    if check:
        if stale:
            sys.stderr.write(
                "gen_recipes: recipes out of date (run ./scripts/gen_recipes.py):\n"
            )
            for s in stale:
                sys.stderr.write("  - %s\n" % s)
            return 1
        print("gen_recipes: %d recipes up to date." % len(latest))
        return 0

    print("gen_recipes: generated %d component recipes (%d changed)." % (len(latest), written))
    return 0


if __name__ == "__main__":
    sys.exit(main())
