#!/usr/bin/env python3
#/**
# * Copyright 2026 RDK Management
# *
# * Licensed under the Apache License, Version 2.0 (the "License");
# * you may not use this file except in compliance with the License.
# * You may obtain a copy of the License at
# *
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *
# * SPDX-License-Identifier: Apache-2.0
# */
"""Generate the meta-rdk-halif BitBake recipes, one per released snapshot.

Every released snapshot `<comp>/<X.Y.Z.W>/` is emitted as
  tests/yocto/meta-rdk-halif/recipes-halif/rdk-halif-<comp>/rdk-halif-<comp>_<ver>.bb
with `DEPENDS` derived from the exact sibling libraries that snapshot links.

Dependency versions come from the snapshot's own CMakeLists.txt link names
(`<dep>-v<X.Y.Z.W>-cpp`). release.sh writes those fully resolved - the
interface.yaml `imports:` are the human declaration and may carry `@current`,
which release.sh pins there at freeze time - so the link names are the ground
truth of what the committed C++ was built against.

All released versions are emitted (PN `rdk-halif-<comp>`, PV `<ver>`), so a
consuming build configuration selects a component's version with
`PREFERRED_VERSION_rdk-halif-<comp>` (see the meta-vendor / meta-mw examples and
scripts/gen_team_conf.py). With no preference set, BitBake picks the highest
version - the latest cohort - which the generator asserts is internally
consistent so the zero-config default cannot ship broken.

Usage:
  scripts/gen_recipes.py            # regenerate recipes
  scripts/gen_recipes.py --check    # verify recipes are up to date (no writes)
"""
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LAYER = os.path.join(REPO_ROOT, "tests", "yocto", "meta-rdk-halif")
RECIPES_DIR = os.path.join(LAYER, "recipes-halif")

VER_RE = re.compile(r"^\d+\.\d+\.\d+\.\d+$")
LINK_RE = re.compile(r"([a-z0-9]+)-v(\d+\.\d+\.\d+\.\d+)-cpp")


def version_tuple(ver):
    return tuple(int(p) for p in ver.split("."))


def parse_deps(comp, ver):
    """Return [(dep_comp, dep_ver), ...] the snapshot links, from its CMakeLists."""
    cml = os.path.join(REPO_ROOT, comp, ver, "CMakeLists.txt")
    deps = set()
    with open(cml) as fh:
        text = fh.read()
    for block in re.findall(r"target_link_libraries\(([^)]*)\)", text):
        for dep, dver in LINK_RE.findall(block):
            if dep != comp:
                deps.add((dep, dver))
    return sorted(deps)


def discover_all():
    """Map component -> {version: snapshot_dir} for every released snapshot."""
    found = {}
    for comp in sorted(os.listdir(REPO_ROOT)):
        comp_dir = os.path.join(REPO_ROOT, comp)
        if not os.path.isdir(comp_dir) or comp.startswith("."):
            continue
        for ver in os.listdir(comp_dir):
            snap = os.path.join(comp_dir, ver)
            if VER_RE.match(ver) and os.path.isfile(os.path.join(snap, "CMakeLists.txt")):
                found.setdefault(comp, {})[ver] = snap
    return found


HEADER = """# Auto-generated by scripts/gen_recipes.py for {comp}/{ver}.
# Do not hand-edit - regenerate with: ./scripts/gen_recipes.py
"""

BODY = """\
SUMMARY = "RDK HAL AIDL interface library: {comp} (v{ver})"

HALIF_MODULE = "{comp}"
HALIF_VERSION = "{ver}"
PV = "{ver}"
{depends}
inherit rdk-halif-module
"""


def recipe_text(comp, ver, deps):
    if deps:
        dep_line = (
            "\n# Links: {raw}\nDEPENDS += \"{names}\"\n".format(
                raw=", ".join("%s@%s" % (d, v) for d, v in deps),
                names=" ".join("rdk-halif-%s" % d for d, _ in deps),
            )
        )
    else:
        dep_line = "\n# No sibling dependencies - links only the Binder SDK.\n"
    return HEADER.format(comp=comp, ver=ver) + BODY.format(comp=comp, ver=ver, depends=dep_line)


def check_consistency(found):
    """Return a list of consistency errors (empty when clean)."""
    errors = []
    latest = {c: max(v, key=version_tuple) for c, v in found.items()}
    for comp, versions in found.items():
        for ver in versions:
            for dep, dver in parse_deps(comp, ver):
                if dep not in found:
                    errors.append("%s@%s links unknown component %s" % (comp, ver, dep))
                elif dver not in found[dep]:
                    errors.append(
                        "%s@%s links %s@%s but no such released snapshot exists"
                        % (comp, ver, dep, dver)
                    )
                # Guard the zero-config default (BitBake picks highest PV):
                # the latest cohort must reference the latest of each dep.
                elif ver == latest[comp] and dver != latest[dep]:
                    errors.append(
                        "latest %s@%s links %s@%s but latest %s is %s "
                        "(zero-config default cohort would be inconsistent)"
                        % (comp, ver, dep, dver, dep, latest[dep])
                    )
    return errors


def main():
    check = "--check" in sys.argv[1:]
    found = discover_all()

    errors = check_consistency(found)
    if errors:
        sys.stderr.write("gen_recipes: consistency errors:\n")
        for e in errors:
            sys.stderr.write("  - %s\n" % e)
        return 2

    pairs = [(c, v) for c in found for v in found[c]]
    stale = []
    written = 0
    for comp, ver in sorted(pairs):
        text = recipe_text(comp, ver, parse_deps(comp, ver))
        out_dir = os.path.join(RECIPES_DIR, "rdk-halif-%s" % comp)
        out = os.path.join(out_dir, "rdk-halif-%s_%s.bb" % (comp, ver))
        existing = open(out).read() if os.path.isfile(out) else None
        if existing == text:
            continue
        if check:
            stale.append(os.path.relpath(out, REPO_ROOT))
            continue
        os.makedirs(out_dir, exist_ok=True)
        with open(out, "w") as fh:
            fh.write(text)
        written += 1
        print("  wrote %s" % os.path.relpath(out, REPO_ROOT))

    if check:
        if stale:
            sys.stderr.write("gen_recipes: recipes out of date (run ./scripts/gen_recipes.py):\n")
            for s in stale:
                sys.stderr.write("  - %s\n" % s)
            return 1
        print("gen_recipes: %d recipes up to date." % len(pairs))
        return 0

    print("gen_recipes: generated %d recipes across %d components (%d changed)."
          % (len(pairs), len(found), written))
    return 0


if __name__ == "__main__":
    sys.exit(main())
