#!/usr/bin/env python3
#/**
# * Copyright 2026 RDK Management
# *
# * Licensed under the Apache License, Version 2.0 (the "License");
# * you may not use this file except in compliance with the License.
# * You may obtain a copy of the License at
# *
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *
# * SPDX-License-Identifier: Apache-2.0
# */
"""Generate a build-configuration include from a per-team versions manifest.

A team (vendor or middleware) pins the component versions its build configuration
uses in a manifest (versions_vendor.yaml / versions_mw.yaml). This tool turns
that manifest into the `.inc` its parent layer requires: the role, the install
destinations, and one `HALIF_VERSION:pn-rdk-halif-<comp>` per selected component.
Vendor and MW diverge simply by pinning different versions.

The cohort is validated as a closure: every selected component's linked sibling
dependencies must also be selected at the exact linked version, so a manifest
cannot pin an inconsistent set (e.g. hdmicec@0.1.0.0 with common@0.1.0.0 when
hdmicec links common@0.2.0.0).

Usage:
  scripts/gen_team_conf.py <manifest.yaml> --role vendor|mw \\
      [--libdir <path>] [--incdir <path>] -o <out.inc>
  scripts/gen_team_conf.py <manifest.yaml> --role ... -o <out.inc> --check
"""
import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_recipes import parse_deps, discover_all  # noqa: E402


def parse_manifest(path):
    """Return {component: version} from the manifest's `components:` map."""
    sel = {}
    in_comp = False
    with open(path) as fh:
        for line in fh:
            s = line.rstrip("\n")
            if not s.strip() or s.strip().startswith("#"):
                continue
            if re.match(r"^components:\s*$", s):
                in_comp = True
                continue
            if in_comp:
                m = re.match(r"^\s+([A-Za-z0-9_]+):\s*(\S+)\s*$", s)
                if m:
                    sel[m.group(1)] = m.group(2)
                elif not s[0].isspace():
                    in_comp = False
    return sel


def validate(sel, found):
    """Return errors if the selected cohort is not a consistent closure."""
    errors = []
    for comp, ver in sorted(sel.items()):
        if comp not in found or ver not in found[comp]:
            errors.append("%s@%s is not a released snapshot" % (comp, ver))
            continue
        for dep, dver in parse_deps(comp, ver):
            if sel.get(dep) != dver:
                errors.append(
                    "%s@%s links %s@%s but the manifest selects %s=%s"
                    % (comp, ver, dep, dver, dep, sel.get(dep, "(unset)"))
                )
    return errors


def render(sel, role, libdir, incdir, manifest_name):
    lines = [
        "# Auto-generated by scripts/gen_team_conf.py from %s." % manifest_name,
        "# Do not hand-edit - regenerate from the versions manifest.",
        "",
        'HALIF_ROLE = "%s"' % role,
        'HALIF_LIBDIR = "%s"' % libdir,
        'HALIF_INCDIR = "%s"' % incdir,
        "",
    ]
    for comp, ver in sorted(sel.items()):
        lines.append('HALIF_VERSION:pn-rdk-halif-%s = "%s"' % (comp, ver))
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("manifest")
    ap.add_argument("--role", required=True, choices=["vendor", "mw"])
    ap.add_argument("--libdir", default="${libdir}/halif")
    ap.add_argument("--incdir", default="${includedir}/halif")
    ap.add_argument("-o", "--out", required=True)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    found = discover_all()
    sel = parse_manifest(args.manifest)
    if not sel:
        sys.stderr.write("gen_team_conf: no components selected in %s\n" % args.manifest)
        return 2

    errors = validate(sel, found)
    if errors:
        sys.stderr.write("gen_team_conf: inconsistent cohort in %s:\n" % args.manifest)
        for e in errors:
            sys.stderr.write("  - %s\n" % e)
        return 2

    text = render(sel, args.role, args.libdir, args.incdir, os.path.basename(args.manifest))
    existing = open(args.out).read() if os.path.isfile(args.out) else None
    if args.check:
        if existing != text:
            sys.stderr.write("gen_team_conf: %s is out of date (regenerate)\n" % args.out)
            return 1
        print("gen_team_conf: %s up to date (%d components)." % (args.out, len(sel)))
        return 0

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as fh:
        fh.write(text)
    print("gen_team_conf: wrote %s (%d components, role=%s)." % (args.out, len(sel), args.role))
    return 0


if __name__ == "__main__":
    sys.exit(main())
