#!/usr/bin/env python3
#/**
# * Copyright 2026 RDK Management
# *
# * Licensed under the Apache License, Version 2.0 (the "License");
# * you may not use this file except in compliance with the License.
# * You may obtain a copy of the License at
# *
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *
# * SPDX-License-Identifier: Apache-2.0
# */
"""Generate the meta-rdk-halif default component list (HALIF_COMPONENTS).

The single `rdk-halif` recipe builds the components named in HALIF_COMPONENTS.
This writes the default list - every released component - into
halif-components.inc, and asserts the latest cohort (the zero-config default,
built when nothing is overridden) is internally consistent, so it cannot ship
broken.

Usage:
  scripts/gen_recipes.py            # regenerate the component list
  scripts/gen_recipes.py --check    # verify it is up to date (no writes)
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from halif_plan import REPO_ROOT, released_versions, links, all_components  # noqa: E402

INC = os.path.join(
    REPO_ROOT, "tests", "yocto", "meta-rdk-halif",
    "recipes-halif", "rdk-halif", "halif-components.inc",
)

HEADER = "# Auto-generated by scripts/gen_recipes.py - do not hand-edit.\n"


def check_consistency(comps):
    """The latest cohort (default build) must link the latest of each dep."""
    latest = {c: released_versions(c)[-1] for c in comps}
    errors = []
    for c in comps:
        for dep, dver in links(c, latest[c]).items():
            if dep not in latest:
                errors.append("latest %s links unknown component %s" % (c, dep))
            elif dver != latest[dep]:
                errors.append(
                    "latest %s@%s links %s@%s but latest %s is %s "
                    "(zero-config default cohort would be inconsistent)"
                    % (c, latest[c], dep, dver, dep, latest[dep])
                )
    return errors


def main():
    check = "--check" in sys.argv[1:]
    comps = all_components()

    errors = check_consistency(comps)
    if errors:
        sys.stderr.write("gen_recipes: consistency errors:\n")
        for e in errors:
            sys.stderr.write("  - %s\n" % e)
        return 2

    text = HEADER + 'HALIF_COMPONENTS ??= "%s"\n' % " ".join(comps)
    current = open(INC).read() if os.path.isfile(INC) else None

    if check:
        if current != text:
            sys.stderr.write("gen_recipes: %s is out of date (run ./scripts/gen_recipes.py)\n"
                             % os.path.relpath(INC, REPO_ROOT))
            return 1
        print("gen_recipes: component list up to date (%d components)." % len(comps))
        return 0

    os.makedirs(os.path.dirname(INC), exist_ok=True)
    with open(INC, "w") as fh:
        fh.write(text)
    print("gen_recipes: wrote %s (%d components)." % (os.path.relpath(INC, REPO_ROOT), len(comps)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
