# Auto-generated by scripts/gen_recipes.py for audiodecoder/0.2.0.0.
# Do not hand-edit - regenerate with: ./scripts/gen_recipes.py
SUMMARY = "RDK HAL AIDL interface library: audiodecoder (v0.2.0.0)"

HALIF_MODULE = "audiodecoder"
HALIF_VERSION = "0.2.0.0"
PV = "0.2.0.0"

# Links: common@0.2.0.0
DEPENDS += "rdk-halif-common"

inherit rdk-halif-module
