/*
 * If not stated otherwise in this file or this component's LICENSE file the
 * following copyright and licenses apply:
 *
 * Copyright 2026 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.rdk.hal.audiosink;

/**
 * @brief     What describes an occurrence audiosink raised.
 * @author    Gerald Weatherup
 *
 * THIS FILE IS GENERATED by scripts/kvcc.py from
 * audiosink/kvc/current/audiosink.kvc (vocabulary 1.0,
 * schema 1). Do not edit: declare the key there and
 * regenerate, so an identifier is derived rather than typed.
 */

/**
 * @brief What describes an occurrence audiosink raised.
 *
 * An attribute locates and classifies an occurrence rather than measuring
 * it, so its identifier composes without a kind term. A value an occurrence
 * measured does carry a kind. Both appear in MetricEvent, in the array that
 * says which it is.
 */

@VintfStability
@Backing(type="long")
enum MetricEventAttribute
{

    /**
     * `av.audio_sink.underflow.trigger` — none. What caused this episode,
     * which is what distinguishes an expected starvation from a defect.
     */
    UNDERFLOW_TRIGGER = 0x09a5326ee175d8ec,

    /**
     * `av.audio_sink.underflow_end.duration_ms` — ms, current. Length of the
     * episode this closes, from start to resume. Not cumulative —
     * underflow_duration_ms carries the running total.
     */
    UNDERFLOW_END_DURATION_MS = 0x6ca9e3e276c7ece3,

    /**
     * `av.audio_sink.silence.elapsed_ms` — ms, current. Silence already
     * elapsed at the crossing, which is silence_threshold_ms within one
     * detection interval. Present so a consumer need not assume the threshold
     * it was configured with is the one in force.
     */
    SILENCE_ELAPSED_MS = 0x25e863e9bb2888c4,

    /**
     * `av.audio_sink.silence_end.duration_ms` — ms, current. Length of the
     * whole period this closes, from the onset of silence rather than from
     * the crossing. Not cumulative — silence_duration_ms carries the running
     * total.
     */
    SILENCE_END_DURATION_MS = 0x0292d87cd65e7240,
}
