/*
 * If not stated otherwise in this file or this component's LICENSE file the
 * following copyright and licenses apply:
 *
 * Copyright 2026 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.rdk.hal.audiosink;

/**
 * @brief     The figures audiosink measures.
 * @author    Gerald Weatherup
 *
 * THIS FILE IS GENERATED by scripts/kvcc.py from
 * audiosink/kvc/current/audiosink.kvc (vocabulary 1.0,
 * schema 1). Do not edit: declare the key there and
 * regenerate, so an identifier is derived rather than typed.
 */

/**
 * @brief The figures audiosink measures.
 *
 * A value carries aggregation semantics, so its identifier composes with its
 * kind as well as its unit. Serving one in the wrong unit, or reading it on
 * the wrong cadence for its kind, is then a mismatch a consumer can detect
 * rather than a plausible wrong number.
 */

@VintfStability
@Backing(type="long")
enum Metric
{

    /**
     * `av.audio_sink.underflowed` — episodes, counter. Count of audio buffer-
     * underflow episodes, one per episode start, where an episode starts when
     * there is no decoded audio to present and ends when output resumes. The
     * counterpart of av.video_sink.underflowed — without it an audio
     * underflow rate cannot be computed at all.
     */
    UNDERFLOWED = 0x142f899619c8c4a9,

    /**
     * `av.audio_sink.underflow_duration_ms` — ms, counter. Cumulative time
     * the audio path was starved of decoded data. Paired with underflowed, so
     * the mean episode length is this divided by that.
     */
    UNDERFLOW_DURATION_MS = 0x4ce68288bc2f93b2,

    /**
     * `av.audio_sink.silence_duration_ms` — ms, counter. Cumulative emitted
     * digital silence, counting only periods that reached
     * silence_threshold_ms. Distinguishes an unexpected absence of audio
     * output from starvation, which is underflow_duration_ms.
     */
    SILENCE_DURATION_MS = 0x09fdcdf6715ef048,

    /**
     * `av.audio_sink.silence_event_count` — events, counter. Count of
     * completed digital-silence periods that reached silence_threshold_ms.
     * Paired with silence_duration_ms, so the mean silence length is that
     * divided by this.
     */
    SILENCE_EVENT_COUNT = 0x357a57be2601412e,

    /**
     * `av.audio_sink.buffer_depth_ms` — ms, current. Buffered decoded audio
     * ahead of the play position now. A live sample re-read each capture
     * rather than a cumulative figure. This is SoC- and use-case-specific, so
     * compare it against itself over time rather than across products.
     */
    BUFFER_DEPTH_MS = 0x1aea4fc8a27262b7,

    /**
     * `av.audio_sink.last_underflow_trigger` — none, current. Cause of the
     * most recent audio underflow episode, from the same vocabulary as
     * av.video_sink.last_underflow_trigger.
     */
    LAST_UNDERFLOW_TRIGGER = 0x40771a4a2b2ee087,

    /**
     * `av.audio_sink.last_underflow_duration_ms` — ms, current. Length of the
     * most recent completed audio underflow episode. Read with underflowed
     * and underflow_duration_ms, which give the count and the total.
     */
    LAST_UNDERFLOW_DURATION_MS = 0x638f410fc657c525,

    /**
     * `av.audio_sink.last_silence_duration_ms` — ms, current. Length of the
     * most recent completed digital-silence period. Read with
     * silence_event_count and silence_duration_ms.
     */
    LAST_SILENCE_DURATION_MS = 0x1cf88c9352312e83,

    /**
     * `av.audio_sink.silence_threshold_ms` — ms, config. Shortest digital-
     * silence period that counts as one. Silence is normal output — a gap
     * between programmes, a muted stream, a silent passage — so this is the
     * line between that and a fault worth reporting. Default 500 ms, and set
     * by product configuration rather than over this interface. Reading it is
     * what the key is for: silence_duration_ms and silence_event_count count
     * only periods that reached it, so neither is interpretable without it.
     */
    SILENCE_THRESHOLD_MS = 0x02c4359649749c70,
}
