/*
 * If not stated otherwise in this file or this component's LICENSE file the
 * following copyright and licenses apply:
 *
 * Copyright 2026 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.rdk.hal.audiosink;

/**
 * @brief     The occurrences audiosink raises.
 * @author    Gerald Weatherup
 *
 * THIS FILE IS GENERATED by scripts/kvcc.py from
 * audiosink/kvc/current/audiosink.kvc (vocabulary 1.0,
 * schema 1). Do not edit: declare the key there and
 * regenerate, so an identifier is derived rather than typed.
 */

/**
 * @brief The occurrences audiosink raises.
 *
 * MetricEvent.eventId carries one of these. An occurrence is pushed because
 * a read cannot carry it: a condition that began and ended between two reads
 * is invisible to a reader however fast it polls.
 */

@VintfStability
@Backing(type="long")
enum MetricEventKind
{

    /**
     * `av.audio_sink.underflow` — Raised at the START of a starvation
     * episode, the instant there is nothing to present at render time.
     * Exactly one underflow_end closes it.
     */
    UNDERFLOW = 0x04bd3affe9b839b9,

    /**
     * `av.audio_sink.underflow_end` — Raised when presentation resumes,
     * closing the episode the preceding underflow opened.
     */
    UNDERFLOW_END = 0x345a8515da6f3c17,

    /**
     * `av.audio_sink.silence` — Raised when digital silence has continued for
     * silence_threshold_ms, NOT when it began. Silence is ordinary output, so
     * the threshold is what separates a gap between programmes from a fault,
     * and below it nothing is raised. Raising at the crossing rather than at
     * the close is what makes a silence that is still going reportable while
     * it is still going.
     */
    SILENCE = 0x2f6b025842e93317,

    /**
     * `av.audio_sink.silence_end` — Raised when audio resumes, closing the
     * period the preceding silence opened. A period that never crossed the
     * threshold raises neither.
     */
    SILENCE_END = 0x7d6df873d14dbb94,
}
