/*
 * If not stated otherwise in this file or this component's LICENSE file the
 * following copyright and licenses apply:
 *
 * Copyright 2026 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.rdk.hal.videosink;

/**
 * @brief     What describes an occurrence videosink raised.
 * @author    Gerald Weatherup
 *
 * THIS FILE IS GENERATED by scripts/kvcc.py from
 * videosink/kvc/current/videosink.kvc (vocabulary 1.0,
 * schema 1). Do not edit: declare the key there and
 * regenerate, so an identifier is derived rather than typed.
 */

/**
 * @brief What describes an occurrence videosink raised.
 *
 * An attribute locates and classifies an occurrence rather than measuring
 * it, so its identifier composes without a kind term. A value an occurrence
 * measured does carry a kind. Both appear in MetricEvent, in the array that
 * says which it is.
 */

@VintfStability
@Backing(type="long")
enum MetricEventAttribute
{

    /**
     * `av.video_sink.underflow.trigger` — none. What caused this episode,
     * which is what distinguishes an expected starvation from a defect.
     */
    UNDERFLOW_TRIGGER = 0x13e2fbe05ae793e6,

    /**
     * `av.video_sink.first_frame_presented.pts_ms` — ms. PTS of the frame
     * that reached presentation. Absent where the SoC cannot derive a PTS.
     */
    FIRST_FRAME_PRESENTED_PTS_MS = 0x781403dd60990bb7,

    /**
     * `av.video_sink.quality_threshold_crossed.metric` — none. Which counter
     * crossed its threshold.
     */
    QUALITY_THRESHOLD_CROSSED_METRIC = 0x118b55b16b7e25dd,

    /**
     * `av.video_sink.quality_threshold_crossed.pts_ms` — ms. Stream PTS at
     * the crossing. Absent where no PTS is derivable.
     */
    QUALITY_THRESHOLD_CROSSED_PTS_MS = 0x3f8d8a1a4f44786a,

    /**
     * `av.video_sink.underflow_end.duration_ms` — ms, current. Length of the
     * episode this closes, from start to resume. Not cumulative —
     * underflow_duration_ms carries the running total.
     */
    UNDERFLOW_END_DURATION_MS = 0x2045159af585515b,

    /**
     * `av.video_sink.quality_threshold_crossed.count` — frames, current. How
     * many frames the crossing covered.
     */
    QUALITY_THRESHOLD_CROSSED_COUNT = 0x09ec7999c4c03f17,
}
