/*
 * If not stated otherwise in this file or this component's LICENSE file the
 * following copyright and licenses apply:
 *
 * Copyright 2026 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.rdk.hal.videosink;

/**
 * @brief     The figures videosink measures.
 * @author    Gerald Weatherup
 *
 * THIS FILE IS GENERATED by scripts/kvcc.py from
 * videosink/kvc/current/videosink.kvc (vocabulary 1.0,
 * schema 1). Do not edit: declare the key there and
 * regenerate, so an identifier is derived rather than typed.
 */

/**
 * @brief The figures videosink measures.
 *
 * A value carries aggregation semantics, so its identifier composes with its
 * kind as well as its unit. Serving one in the wrong unit, or reading it on
 * the wrong cadence for its kind, is then a mismatch a consumer can detect
 * rather than a plausible wrong number.
 */

@VintfStability
@Backing(type="long")
enum Metric
{

    /**
     * `av.video_sink.frames_received` — frames, counter. Decoded frames
     * received from the decoder to be presented.
     */
    FRAMES_RECEIVED = 0x524c81ef37d81082,

    /**
     * `av.video_sink.frames_presented` — frames, counter. Frames handed to
     * display scanout for presentation, one per successful render.
     */
    FRAMES_PRESENTED = 0x7f36b75533d5db3a,

    /**
     * `av.video_sink.frames_dropped_late` — frames, counter. Frames dropped
     * because their PTS deadline against the render clock had passed by more
     * than one display frame interval at the sink render check — too late to
     * show. Sink render-decision internal.
     */
    FRAMES_DROPPED_LATE = 0x7682bfb371ecc4d5,

    /**
     * `av.video_sink.frames_dropped_frc` — frames, counter. Frames dropped by
     * frame-rate conversion when the source rate exceeds the display rate,
     * which is cadence decimation rather than lateness.
     */
    FRAMES_DROPPED_FRC = 0x6c43fb5584823d18,

    /**
     * `av.video_sink.frames_repeated_frc` — frames, counter. Frames held for
     * more than one display interval by frame-rate conversion when the source
     * rate is below the display rate. Normal content cadence, and not a
     * freeze.
     */
    FRAMES_REPEATED_FRC = 0x72b9db4bfce6f2ab,

    /**
     * `av.video_sink.frames_repeated_missing_frame` — frames, counter. Frames
     * repeated to cover a missing next frame — the sink had no new decoded
     * frame ready at render time. This is starvation cover, and it is what
     * freeze_duration_ms integrates.
     */
    FRAMES_REPEATED_MISSING_FRAME = 0x5a652c2dcf72deac,

    /**
     * `av.video_sink.underflowed` — episodes, counter. Count of video buffer-
     * underflow episodes. One per episode start, where an episode starts when
     * there is no frame to present at render time and ends when a new frame
     * is presented.
     */
    UNDERFLOWED = 0x6804c05ae6533181,

    /**
     * `av.video_sink.underflow_duration_ms` — ms, counter. Cumulative wall-
     * clock time across all video underflow episodes. Paired with
     * underflowed, so the mean episode length is this divided by that. An
     * underflow episode manifests on screen as a freeze.
     */
    UNDERFLOW_DURATION_MS = 0x23e55a88f5bbbd94,

    /**
     * `av.video_sink.freeze_duration_ms` — ms, counter. Cumulative on-screen
     * time the same frame was held to cover a missing frame, which is the
     * customer-visible freeze — the time integral of
     * frames_repeated_missing_frame. Excludes frame-rate-conversion cadence
     * repeats, which are not freezes.
     */
    FREEZE_DURATION_MS = 0x1c86c5dfa4db5108,

    /**
     * `av.video_sink.freeze_event_count` — events, counter. Count of freeze
     * episodes, one per episode start. Paired with freeze_duration_ms, so the
     * mean freeze length is that divided by this.
     */
    FREEZE_EVENT_COUNT = 0x5196f6826e91a801,

    /**
     * `av.video_sink.max_freeze_duration_ms` — ms, high_water. Longest single
     * freeze episode observed. A monotone non-decreasing high-water mark over
     * the life of the resource, and read-only: a maximum cannot be recovered
     * by differencing two maxima, so a consumer wanting the worst freeze
     * within its own reporting window tracks that itself from
     * last_freeze_duration_ms rather than resetting a figure other readers
     * share.
     */
    MAX_FREEZE_DURATION_MS = 0x088d619c00c1c539,

    /**
     * `av.video_sink.render_latency_sum_us` — us, counter. Running sum of
     * per-frame render latency, from a frame arriving at the sink input to
     * being presented to scanout. Paired with frames_presented.
     */
    RENDER_LATENCY_SUM_US = 0x75f862796424b00d,

    /**
     * `av.video_sink.buffer_depth_ms` — ms, current. Buffered decoded media
     * ahead of the present position now — the sum of presentation durations
     * of frames queued but not yet presented. A live sample re-read each
     * capture rather than a cumulative figure. This is SoC- and use-case-
     * specific, so compare it against itself over time rather than across
     * products.
     */
    BUFFER_DEPTH_MS = 0x111d82c20cb9e693,

    /**
     * `av.video_sink.last_underflow_trigger` — none, current. Cause of the
     * most recent underflow episode, which is what distinguishes an expected
     * starvation from a defect.
     */
    LAST_UNDERFLOW_TRIGGER = 0x03210d8159685756,

    /**
     * `av.video_sink.last_underflow_duration_ms` — ms, current. Length of the
     * most recent completed underflow episode. Read with underflowed and
     * underflow_duration_ms, which give the count and the total.
     */
    LAST_UNDERFLOW_DURATION_MS = 0x7b1ed4a908e8ef1b,

    /**
     * `av.video_sink.last_dropped_frame_pts_ms` — ms, current. Stream PTS of
     * the most recently dropped frame, within one frame interval, whichever
     * drop axis it fell on. This is what turns a drop count into a locatable
     * defect. Left undeclared where no PTS is derivable.
     */
    LAST_DROPPED_FRAME_PTS_MS = 0x0e6d081eed2918dd,

    /**
     * `av.video_sink.last_freeze_pts_ms` — ms, current. Stream PTS at which
     * the most recent freeze episode began, within one frame interval. Does
     * for a freeze what last_dropped_frame_pts_ms does for a drop. Left
     * undeclared where no PTS is derivable.
     */
    LAST_FREEZE_PTS_MS = 0x42cfffc003874fd4,

    /**
     * `av.video_sink.last_freeze_duration_ms` — ms, current. Length of the
     * most recent completed freeze episode. Read with freeze_event_count and
     * freeze_duration_ms for the count and the total, and with
     * max_freeze_duration_ms for the worst.
     */
    LAST_FREEZE_DURATION_MS = 0x3e53a4af6a16f1ce,

    /**
     * `av.video_sink.first_frame_presented_pts_ms` — ms, current. PTS of the
     * first frame to reach presentation, set at session start and re-set
     * after each seek or flush. This is the hardware's contribution to time-
     * to-first-frame; whatever elapsed above the HAL before decode began is
     * observed by the party that started the session.
     */
    FIRST_FRAME_PRESENTED_PTS_MS = 0x56eaeb10709bcdd8,
}
