# Auto-generated by scripts/gen_recipes.py for avbuffer/0.2.0.0.
# Do not hand-edit - regenerate with: ./scripts/gen_recipes.py
SUMMARY = "RDK HAL AIDL interface library: avbuffer (v0.2.0.0)"

HALIF_MODULE = "avbuffer"
HALIF_VERSION = "0.2.0.0"
PV = "0.2.0.0"

# Links: audiodecoder@0.2.0.0, videodecoder@0.2.0.0
DEPENDS += "rdk-halif-audiodecoder rdk-halif-videodecoder"

inherit rdk-halif-module
