# Auto-generated by scripts/gen_recipes.py for videodecoder/0.1.0.0.
# Do not hand-edit - regenerate with: ./scripts/gen_recipes.py
SUMMARY = "RDK HAL AIDL interface library: videodecoder (v0.1.0.0)"

HALIF_MODULE = "videodecoder"
HALIF_VERSION = "0.1.0.0"
PV = "0.1.0.0"

# Links: common@0.1.0.0
DEPENDS += "rdk-halif-common"

inherit rdk-halif-module
