# Auto-generated by scripts/gen_recipes.py for videosink/0.2.0.0.
# Do not hand-edit - regenerate with: ./scripts/gen_recipes.py
SUMMARY = "RDK HAL AIDL interface library: videosink (v0.2.0.0)"

HALIF_MODULE = "videosink"
HALIF_VERSION = "0.2.0.0"
PV = "0.2.0.0"

# Links: avclock@0.2.0.0, common@0.2.0.0, videodecoder@0.2.0.0
DEPENDS += "rdk-halif-avclock rdk-halif-common rdk-halif-videodecoder"

inherit rdk-halif-module
