/*
 * If not stated otherwise in this file or this component's LICENSE file the
 * following copyright and licenses apply:
 *
 * Copyright 2026 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.rdk.hal.avclock;

/**
 * @brief     The figures avclock measures.
 * @author    Gerald Weatherup
 *
 * THIS FILE IS GENERATED by scripts/kvcc.py from
 * avclock/kvc/current/avclock.kvc (vocabulary 1.0,
 * schema 1). Do not edit: declare the key there and
 * regenerate, so an identifier is derived rather than typed.
 */

/**
 * @brief The figures avclock measures.
 *
 * A value carries aggregation semantics, so its identifier composes with its
 * kind as well as its unit. Serving one in the wrong unit, or reading it on
 * the wrong cadence for its kind, is then a mismatch a consumer can detect
 * rather than a plausible wrong number.
 */

@VintfStability
@Backing(type="long")
enum Metric
{

    /**
     * `av.clock.sync_offset_ms` — ms, current. The driver's predicted current
     * audio-versus-video presentation offset. Positive when audio leads,
     * negative when video leads. A live sample rather than a cumulative
     * figure.
     */
    SYNC_OFFSET_MS = 0x0853e5868c5f2bd8,

    /**
     * `av.clock.sync_max_abs_offset_ms` — ms, high_water. Largest absolute
     * sync_offset_ms observed. A monotone non-decreasing high-water mark over
     * the life of the resource, and read-only: a maximum cannot be recovered
     * by differencing two maxima, so a consumer wanting the worst excursion
     * within its own reporting window tracks that itself from sync_offset_ms
     * rather than resetting a figure other readers share.
     */
    SYNC_MAX_ABS_OFFSET_MS = 0x20d08f573aeb1229,

    /**
     * `av.clock.sync_time_over_threshold_ms` — ms, counter. Cumulative time
     * the absolute sync_offset_ms exceeded sync_threshold_ms — the time
     * integral of out-of-sync operation.
     */
    SYNC_TIME_OVER_THRESHOLD_MS = 0x323c3766c9e3638c,

    /**
     * `av.clock.sync_threshold_ms` — ms, config. The offset magnitude beyond
     * which playback counts as out of sync. This is the threshold
     * sync_time_over_threshold_ms integrates against and
     * sync_max_abs_offset_ms is judged by, so declaring either of those
     * without this leaves both uninterpretable — reading it is what the key
     * is for. The value is set by product configuration rather than over this
     * interface, so a consumer never has to assume the threshold it was built
     * against is the one in force.
     */
    SYNC_THRESHOLD_MS = 0x4c981a6fd5bbf977,

    /**
     * `av.clock.resync_count` — events, counter. Count of A/V-sync
     * corrections the clock applied, one per discrete realignment of audio
     * and video.
     */
    RESYNC_COUNT = 0x1e11b09c212e1a59,

    /**
     * `av.clock.resync_magnitude_sum_ms` — ms, counter. Sum of the absolute
     * magnitude of each resync correction. Clock-internal, and paired with
     * resync_count so the mean correction size is this divided by that.
     */
    RESYNC_MAGNITUDE_SUM_MS = 0x7be51ba179aa2379,
}
